# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  buildConfiguration: 'Release'

steps:
#- script: dotnet build **/*.csproj --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'Framework/**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'Framework/**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Framework/Tests/Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'